"""Test a controlled twilight grade in the cloned creek scene."""
import unreal

assert 'CapraElectricDreamStudy' in unreal.Paths.project_dir()
MAP='/Game/Levels/PCG/ElectricDreams_PCGCloseRange'
world=unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem).get_editor_world()
assert MAP in world.get_path_name()
actors=unreal.EditorLevelLibrary.get_all_level_actors()
sun=next(a for a in actors if isinstance(a,unreal.DirectionalLight))
sky=next(a for a in actors if isinstance(a,unreal.SkyLight))
sun.get_components_by_class(unreal.DirectionalLightComponent)[0].set_editor_property('intensity',1500.0)
sky.light_component.set_editor_property('intensity',0.15)
signal=next(a for a in actors if a.get_actor_label()=='ED_Signal_Light')
signal.point_light_component.set_editor_property('intensity',15000.0)
signal.point_light_component.set_editor_property('attenuation_radius',900.0)
violet=unreal.EditorLevelLibrary.spawn_actor_from_class(unreal.PointLight,unreal.Vector(89600,-6350,2200))
violet.set_actor_label('ED_Violet_Rim')
violet.point_light_component.set_editor_property('light_color',unreal.Color(r=125,g=65,b=255,a=255))
violet.point_light_component.set_editor_property('intensity',12000.0)
violet.point_light_component.set_editor_property('attenuation_radius',1800.0)
assert unreal.get_editor_subsystem(unreal.LevelEditorSubsystem).save_current_level()

subsystem=unreal.get_editor_subsystem(unreal.MoviePipelineQueueSubsystem)
assert not subsystem.is_rendering()
queue=subsystem.get_queue()
assert all(j.job_name.startswith('Capra Electric Dreams') for j in queue.get_jobs())
queue.delete_all_jobs()
seq=unreal.load_asset('/Game/CapraStudy/ElectricDreams/Sequences/LS_EDScout')
job=queue.allocate_new_job(unreal.MoviePipelineExecutorJob)
job.job_name='Capra Electric Dreams 720p twilight scout'
job.sequence=unreal.SoftObjectPath(seq.get_path_name())
job.map=unreal.SoftObjectPath(MAP+'.ElectricDreams_PCGCloseRange')
config=unreal.MoviePipelinePrimaryConfig()
output=config.find_or_add_setting_by_class(unreal.MoviePipelineOutputSetting)
output.set_editor_property('output_directory',unreal.DirectoryPath(path=unreal.Paths.project_saved_dir()+'CapraStudy/EDScoutTwilight720'))
output.set_editor_property('output_resolution',unreal.IntPoint(1280,720))
output.set_editor_property('file_name_format','ScoutTwilight.{frame_number}')
output.set_editor_property('use_custom_playback_range',True)
output.set_editor_property('custom_start_frame',0)
output.set_editor_property('custom_end_frame',1)
output.set_editor_property('output_frame_rate',unreal.FrameRate(30,1))
config.find_or_add_setting_by_class(unreal.MoviePipelineDeferredPassBase)
config.find_or_add_setting_by_class(unreal.MoviePipelineImageSequenceOutput_PNG)
job.set_configuration(config)
executor=subsystem.render_queue_with_executor(unreal.MoviePipelinePIEExecutor)
print('TWILIGHT_SCOUT_STARTED',bool(executor))
