"""Finish the scene if initial setup was interrupted after camera creation."""
import unreal
level=unreal.get_editor_subsystem(unreal.LevelEditorSubsystem)
world=unreal.get_editor_subsystem(unreal.UnrealEditorSubsystem).get_editor_world()
assert 'WorldWakesStudy' in world.get_path_name(),world.get_path_name()
actors=unreal.EditorLevelLibrary.get_all_level_actors()
camera=next(a for a in actors if isinstance(a,unreal.CineCameraActor))
camera.set_actor_location(unreal.Vector(0,-920,260),False,False)
camera.set_actor_rotation(unreal.MathLibrary.find_look_at_rotation(camera.get_actor_location(),unreal.Vector(0,0,15)),False)
cc=camera.get_cine_camera_component()
cc.set_editor_property('current_focal_length',33.0)
cc.set_editor_property('focus_settings',unreal.CameraFocusSettings(focus_method=unreal.CameraFocusMethod.DISABLE))
pp=next((a for a in actors if isinstance(a,unreal.PostProcessVolume)),None)
if not pp:pp=unreal.EditorLevelLibrary.spawn_actor_from_class(unreal.PostProcessVolume,unreal.Vector(0,0,0))
pp.set_actor_label('World wakes grade');pp.set_editor_property('unbound',True)
settings=pp.get_editor_property('settings')
settings.set_editor_property('override_auto_exposure_method',True)
settings.set_editor_property('auto_exposure_method',unreal.AutoExposureMethod.AEM_MANUAL)
settings.set_editor_property('override_auto_exposure_bias',True)
settings.set_editor_property('auto_exposure_bias',.2)
pp.set_editor_property('settings',settings)
assert level.save_current_level()
print('WORLD_READY',world.get_path_name(),[a.get_actor_label() for a in actors])
