// Curated public studio knowledge only. Private second-brain files are never imported.
export const knowledge = [
 {id:'studio',title:'About Capra',url:'index.html#studio',tags:'studio atlanta kris founder location remote',text:'Capra Studios is an independent design and web studio in Atlanta led by Kris Brown. Services include websites, web applications, 3D motion, and AI consulting. Clients work directly with Kris. Remote collaboration is available across the United States.'},
 {id:'web',title:'Websites and applications',url:'index.html#services',tags:'website redesign design application app portal build development',text:'Capra designs and develops websites, custom web applications, product interfaces, and interactive web experiences. Existing websites and applications can be assessed for targeted improvements or a full redesign.'},
 {id:'motion',title:'3D and motion',url:'index.html#services',tags:'animation 3d unreal blender film logo motion',text:'Capra offers 3D animation, brand films, logo motion, and interactive web experiences. Motion can be a standalone project or part of a launch. Concept, duration, delivery formats and included source files are agreed in the project scope.'},
 {id:'agents',title:'Chat and customer service agents',url:'ai-consulting.html',tags:'chat chatbot agent customer service support lead qualification onboarding',text:'Capra designs chat agents for website guidance, onboarding, lead qualification and customer service. Support agents can answer repeat questions, gather request details, route to a person and connect approved actions to business tools. Permissions and human handoffs are defined before deployment.'},
 {id:'rag',title:'Knowledge and RAG systems',url:'ai-consulting.html',tags:'rag retrieval knowledge documents sources policies handbook internal search',text:'Retrieval-augmented generation retrieves relevant passages from approved documents and knowledge bases to give an AI model useful context. Capra can design source references, access controls, content updates and retrieval testing. RAG does not necessarily mean training a new model. This website assistant only has curated public studio knowledge; it cannot search private client files.'},
 {id:'operations',title:'AI business operations',url:'ai-consulting.html#ai-start',tags:'business operations consulting strategy automation automate whole run workflow crm tools integration',text:'AI consulting can cover an operating model across sales, support, administration and delivery. Start by mapping workflows, people, systems and data; prioritize a pilot; test outcomes, permissions and handoffs; monitor and expand. Agent integrations depend on the chosen systems and access. No guarantee of fully autonomous business operation or specific savings is offered.'},
 {id:'pricing',title:'Scope and pricing',url:'index.html#contact',tags:'price pricing cost budget quote timeline deadline availability ownership source files',text:'Projects are scoped and quoted individually. There are no published fixed prices, guaranteed timelines or verified current availability. A proposal sets out deliverables, review stages, timing, source-file ownership and third-party costs. Ask Kris for a quote; do not invent figures or commitments.'},
 {id:'trailgoat',title:'TrailGoat case study',url:'trailgoat.html',tags:'trailgoat portfolio example running product motion',text:'TrailGoat is a founder-built venture, not a claimed external client. Work shown includes its public running product, course/pacing/fueling presentation, interactive product story and block-goat brand film. The public product is at trailgoat.run. No verified commercial outcome metrics are provided.'},
 {id:'squirrel',title:'Purple Squirrel case study',url:'purple-squirrel.html',tags:'purple squirrel portfolio staffing recruiter candidate client portal example',text:'Purple Squirrel is a founder-built staffing product covering candidate submittals, approvals and client review. The case study shows existing product imagery with sample candidate data. The former public URL returned 404 during the September 28 review; do not offer it as a working live demo.'},
 {id:'brief',title:'Start a project',url:'index.html#contact',tags:'contact email meeting project start brief lead follow up',text:'Contact Kris at kris@caprastudios.co. To scope a project ask about the business, goal, current tools or website, intended users, rough budget, and timing. One or two questions at a time. The website brief form lets visitors review and submit their contact details and requirements. Submission is not a booking or a quote. The assistant cannot send email, schedule meetings, access accounts, or take actions in business systems.'}
];
const stop = new Set('a an the i we you our your can could would do does is are it to for of in on with about and or me my want need please help how what'.split(' '));
const tokens = text => [...new Set(text.toLowerCase().match(/[a-z0-9]+/g)||[])].filter(t=>t.length>2&&!stop.has(t));
export function retrieve(query,limit=4){const terms=tokens(query);return knowledge.map(doc=>({doc,score:terms.reduce((n,t)=>n+(tokens(doc.tags).includes(t)?4:0)+(tokens(doc.text).includes(t)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit).map(x=>x.doc);}
