const D=window.CAPRA_DATA,$=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let limit=36;
const tabButtons=[...document.querySelectorAll('[data-tab]')];function tab(name){for(const b of tabButtons)b.classList.toggle('active',b.dataset.tab===name);for(const p of document.querySelectorAll('.panel'))p.hidden=p.id!==name+'-panel';$('#library').scrollIntoView({behavior:'auto'});location.hash=name==='assets'?'library':name;}
tabButtons.forEach(b=>b.addEventListener('click',()=>tab(b.dataset.tab)));$('#lights').onclick=()=>{const on=document.body.classList.toggle('night');$('#lights').textContent=on?'Lights on ○':'Lights off ●';$('#lights').setAttribute('aria-pressed',on);};
for(const val of [...new Set(D.assets.map(a=>a.category))])$('#category').insertAdjacentHTML('beforeend',`<option>${esc(val)}</option>`);for(const val of [...new Set(D.assets.map(a=>a.format))].filter(Boolean).sort())$('#format').insertAdjacentHTML('beforeend',`<option>${esc(val)}</option>`);
function card(a){const i=D.assets.indexOf(a);return `<article class="card"><button class="preview" data-preview="${i}" aria-label="Preview ${esc(a.title)} ${a.theme}"><img loading="lazy" src="${a.thumb}" alt="${esc(a.title)} — ${a.theme}"></button><h3>${esc(a.title)}</h3><p>${a.theme==='day'?'Daylight':a.theme==='night'?'Blacklight':'Color fields'} · ${a.width} × ${a.height}</p><div class="cardlinks"><a href="${a.png}" download>PNG ↓</a><a href="${a.svg}" download>SVG ↓</a>${a.pdf?`<a href="${a.pdf}" download>PDF ↓</a>`:''}</div></article>`;}
function bindPreview(el){el.querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>preview(D.assets[+b.dataset.preview]));}
function render(){const q=$('#search').value.toLowerCase(),cat=$('#category').value,theme=$('#theme').value,fmt=$('#format').value;const all=D.assets.filter(a=>(!cat||a.category===cat)&&(!theme||a.theme===theme)&&(!fmt||a.format===fmt)&&(!q||[a.title,a.category,a.pillar,...a.platforms].join(' ').toLowerCase().includes(q)));$('#count').textContent=`${all.length} matching designs · showing ${Math.min(limit,all.length)}`;$('#assets-grid').innerHTML=all.slice(0,limit).map(card).join('');$('#more').hidden=all.length<=limit;bindPreview($('#assets-grid'));}
for(const id of ['search','category','theme','format'])$('#'+id).addEventListener(id==='search'?'input':'change',()=>{limit=36;render()});$('#more').onclick=()=>{limit+=36;render()};
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Copied to clipboard');}catch(e){toast('Select the text and copy it manually.');}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',2600)}
function preview(a){$('#dialog-content').innerHTML=`<div class="dialog-layout"><img src="${a.png}" alt="${esc(a.title)}"><div><p class="hand">${esc(a.category)}</p><h2>${esc(a.title)}</h2><p class="dialog-meta">${a.width} × ${a.height} · ${a.theme}<br>${esc(a.platforms.join(' · '))}</p><div class="downloads"><a class="button" href="${a.png}" download>Download PNG ↓</a><a href="${a.svg}" download>Editable SVG ↓</a>${a.pdf?`<a href="${a.pdf}" download>Print PDF ↓</a>`:''}</div>${a.caption?`<h3>Matching copy</h3><p class="dialog-copy">${esc(a.caption)}</p><button id="copy-caption">Copy caption</button>`:''}${a.trim?`<p>Trim: ${esc(a.trim)}<br>Bleed: ${esc(a.bleed||'none')}</p>`:''}</div></div>`;if(a.caption)$('#copy-caption').onclick=()=>copy(a.caption);$('#asset-dialog').showModal();}
$('#asset-dialog .close').onclick=()=>$('#asset-dialog').close();$('#asset-dialog').addEventListener('click',e=>{if(e.target===$('#asset-dialog'))$('#asset-dialog').close()});
$('#videos').innerHTML=D.videos.map(v=>`<article class="video-card"><video controls playsinline preload="none" poster="${v.poster}"><source src="${v.video}" type="video/mp4"></video><h3>${esc(v.title)}</h3><p class="small">${v.width} × ${v.height} · ${v.duration.toFixed(1)} seconds · Silent</p><a href="${v.video}" download>Download MP4 ↓</a></article>`).join('');
function renderCopy(){const q=$('#copy-search').value.toLowerCase();const rows=D.posts.filter(p=>!q||(p.headline+' '+p.copy+' '+p.channel).toLowerCase().includes(q));$('#copy-list').innerHTML=rows.map(p=>`<article class="copy-card"><div><h3>${esc(p.headline)}</h3><span class="copy-label">${esc(p.channel)} / ${esc(p.pillar)}</span></div><pre>${esc(p.copy)}</pre><button data-copy="${D.posts.indexOf(p)}">Copy text</button></article>`).join('');$('#copy-list').querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copy(D.posts[+b.dataset.copy].copy));}$('#copy-search').oninput=renderCopy;
$('#bios').innerHTML=Object.entries(D.bios).map(([k,v],i)=>`<article class="bio"><h3>${esc(k)}</h3><pre>${esc(v)}</pre><p class="small">${v.length} characters</p><button data-bio="${i}">Copy bio</button></article>`).join('');$('#bios').querySelectorAll('button').forEach(b=>b.onclick=()=>copy(Object.values(D.bios)[+b.dataset.bio]));
$('#print-grid').innerHTML=D.assets.filter(a=>a.category==='Print').map(card).join('');bindPreview($('#print-grid'));
const carouselNames=[...new Set(D.assets.filter(a=>a.category==='Carousel').map(a=>a.campaign))];$('#carousel-pdfs').innerHTML=carouselNames.map(s=>`<div class="link-card"><h3>${esc(s.slice(3).replaceAll('-',' '))}</h3><a href="carousels/${s}/${s}-day.pdf" download>Daylight PDF ↓</a><a href="carousels/${s}/${s}-night.pdf" download>Blacklight PDF ↓</a></div>`).join('');
$('#signatures').innerHTML=Object.entries(D.signatures).map(([k,v])=>`<article class="sig-card"><h3>${esc(k.replaceAll('-',' '))}</h3><div class="signature-wrap" id="sig-${k}">${v}</div><div class="sig-actions"><button data-sig="${k}">Copy formatted signature</button><a href="email/signature-${k}.html" download>HTML ↓</a></div></article>`).join('');$('#signatures').querySelectorAll('[data-sig]').forEach(b=>b.onclick=async()=>{const k=b.dataset.sig;try{await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([D.signatures[k]],{type:'text/html'}),'text/plain':new Blob([$('#sig-'+k).innerText],{type:'text/plain'})})]);toast('Formatted signature copied');}catch(e){const r=document.createRange();r.selectNodeContents($('#sig-'+k));const s=window.getSelection();s.removeAllRanges();s.addRange(r);toast('Signature selected. Copy and paste into your email app.')}});
const mails=['01-studio-introduction','02-software-conversation','03-web-motion','04-ai-pilot','05-project-story','06-follow-up'];$('#emails').innerHTML=mails.map(n=>`<div class="link-card"><h3>${esc(n.slice(3).replaceAll('-',' '))}</h3><a href="email/${n}.html" target="_blank">Preview HTML ↗</a><a href="email/${n}.txt" download>Plain text ↓</a></div>`).join('');$('#email-grid').innerHTML=D.assets.filter(a=>a.category==='Email').map(card).join('');bindPreview($('#email-grid'));
$('#platforms').innerHTML=Object.entries(D.platforms).map(([k,v],i)=>`<article class="platform-card"><h3>${esc(k)}</h3><p>${esc(v.notes)}</p><button data-format="${v.format}">Browse ${v.format}</button><a href="platform-kits/${String(i+1).padStart(2,'0')}-starter.zip" download>Starter kit ↓</a></article>`).join('');$('#platforms').querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{$('#format').value=b.dataset.format;$('#category').value='';$('#theme').value='';$('#search').value='';limit=36;render();tab('assets');});
render();renderCopy();if(['motion','copy','print','email','platforms','guide'].includes(location.hash.slice(1)))tab(location.hash.slice(1));
